export const PREDEFINED_CITIES = [
    "Mumbai",
    "Delhi NCR",
    "Bangalore",
    "Pune",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Goa",
    "Chandigarh",
    "Jaipur",
    "Kochi",
    "Indore",
    "Lucknow",
    "Guwahati",
    "Bhubaneswar",
    "Bhopal",
    "Kolhapur",
    "Others"
];
