export const PREDEFINED_CITIES = [
    "Mumbai",
    "Delhi NCR",
    "Bengaluru",
    "Pune",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Goa",
    "Chandigarh",
    "Jaipur",
    "Kochi",
    "Indore",
    "Lucknow",
    "Guwahati",
    "Bhubaneswar",
    "Bhopal",
    "Kolhapur",
    "Pan-India / Remote",
    "Others"
];

export const ARTIST_CATEGORIES = [
    "Singer",
    "Band",
    "Anchor",
    "Standup Comedian",
    "Musician",
    "DJ",
    "Dancer",
    "Magician",
    "Speaker",
    "Photographer",
    "Videographer",
    "Others"
];

export const CREATOR_NICHES = [
    'City Pages',
    'College Pages',
    'Student/ Campus Creator',
    'Fashion & Luxury',
    'Tech & Gaming',
    'Travel & Lifestyle',
    'Beauty & Fitness',
    'Food & Beverage',
    'Comedy & Entertainment',
    'Music & Dance',
    'Fitness & Sports',
    'Real Estate',
    'Photography & Filmmaking',
    'Automotive & Moto',
    'Art & Design',
    'Parenting & Family',
    'Podcasts & Media',
    'Meme & Pop Culture',
    'Startup & Entrepreneurship',
    'Finance & Business',
    'Career',
    'Others'
];
